python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 1 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 1 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 1 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 1 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 1 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 2 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 2 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 2 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 2 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 2 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 7 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 7 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 7 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 7 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 7 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 8 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 8 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 8 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 8 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/geqrf/geqrf_kt0_st1_1threads.csv' --test_file '~/app_ed/test_sets/stampede2/geqrf/1threads.csv' --output_file 'figure4_geqrf_sgr.csv' --input_columns 0,1 --data_columns 2 --nlevels 8 --nadaptpts 3 --reg 1e-5 --nrefinements 16
