python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0

python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 5
python gp.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'gp_exafmm.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --gp_kernel_id 0
