python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6

python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 1
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 2
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 3
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 4
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 5
python knn.py --test_set_size 2600 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/exafmm/kt1_nnodes1_test.csv' --output_file 'figure6_exafmm_knn.csv' --input_columns 1,2,3,5,6,7 --data_columns 14 --print_model_parameters 1 --max_spline_degrees 6
