# Plotline: "CPR: Rank 3"
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 4,4,4 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,128,128 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,256,256 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536

# Plotline: "CPR: Rank 6"
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 4,4,4 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,128,128 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,256,256 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536

# Plotline: "CPR: Rank 12"
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 4,4,4 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,128,128 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure3_cpr_gemm' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,256,256 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
