python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 15000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'sgr_bcast.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 16
