python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6

python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 1
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 2
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 3
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 4
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 5
python svm.py --test_set_size 15000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'svm_bcast.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --max_spline_degrees 6
