python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5

python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 0
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 1
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 2
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 3
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 4
python gp.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gp_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --gp_kernel_id 5
