python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 0

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 0

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 0

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 0

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 0



python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 1

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 1

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 1

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 1

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 1



python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 2

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 2

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 2

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 2

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 2



python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 4

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 4

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 4

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 4

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 4



python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 2 --nadaptpts 0 --reg 1e-5 --nrefinements 8

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 0 --reg 1e-5 --nrefinements 8

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 0 --reg 1e-5 --nrefinements 8

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 0 --reg 1e-5 --nrefinements 8

python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 1000 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 0 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 3 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 4 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 5 --nadaptpts 3 --reg 1e-5 --nrefinements 16

python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 0
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 1
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 2
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 4
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 8
python3 sgr.py --test_set_size 65536 --test_set_split_percentage 0.0 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'figure6_gemm_sgr.csv' --input_columns 0,1,2 --data_columns 3 --nlevels 6 --nadaptpts 3 --reg 1e-5 --nrefinements 16
