python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 65536





python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768




python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 16384



python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 8192




python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 4096




python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 2048




python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 1024



python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 512




python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test_64x64x64.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,64,64 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,32,32 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,16,16 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256

python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 1 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 2 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 4 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 8 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
python cpr.py --test_set_size 65536 --test_set_split_percentage 0.0 --interp_map 1,1,1 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'test.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,8,8 --cp_rank 16 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 256
