python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6

python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 1
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 2
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 3
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 4
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 5
python mars.py --test_set_size 9000 --test_set_split_percentage 0.0 --predictor_transform 1,1,0,1,1,1,1,0,0 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/kripke/kt0_nnodes1.csv' --output_file 'figure6_kripke_mars.csv' --input_columns 1,2,3,4,5,9,10,14,15 --data_columns 23 --print_model_parameters 1 --max_spline_degrees 6
