python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 6
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 6
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 6
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 6
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 6
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 6

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 7
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 7
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 7
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 7
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 7
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 7

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 8
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 8
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 8
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 8
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 8
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 8

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 9
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 9
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 9
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 9
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 9
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 9

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 10
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 10
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 10
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 10
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 10
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 10

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 11
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 11
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 11
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 11
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 11
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 11

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 12
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 12
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 12
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 12
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 12
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 12

python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 4 --tree_depth 13
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 8 --tree_depth 13
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 16 --tree_depth 13
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 32 --tree_depth 13
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 64 --tree_depth 13
python gb.py --test_set_size 65536 --test_set_split_percentage 0.0 --predictor_transform 1,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/gemm/1-thread.csv' --test_file '~/app_ed/test_sets/stampede2/gemm/1-thread.csv' --output_file 'gb_gemm.csv' --input_columns 0,1,2 --data_columns 3 --print_model_parameters 1 --ntrees 128 --tree_depth 13
