python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 256 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 512 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 1024 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 2048 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 4096 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 8192 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 16384 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 32768 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6

python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 1
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 2
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 3
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 4
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 5
python knn.py --test_set_size 25000 --test_set_split_percentage 0.0 --predictor_transform 1,1,1,0,0,0,1,1 --response_transform 1 --training_set_size 65536 --training_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1.csv' --test_file '~/app_ed/datasets/stampede2/amg/kt0_nnodes1_test.csv' --output_file 'knn_amg_full_node.csv' --input_columns 0,1,2,3,4,5,9,10 --data_columns 13 --print_model_parameters 1 --nneighbors 6
