# Plotline: "CPR: Rank 3"
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,7,8 --cp_rank 3 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768

# Plotline: "CPR: Rank 6"
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,7,8 --cp_rank 6 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768

# Plotline: "CPR: Rank 12"
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 8,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 16,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 32,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 64,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 128,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
python cpr.py --test_set_size 15000 --test_set_split_percentage 0.0 --interp_map 1,0,0 --response_transform 1 --training_file '~/app_ed/datasets/stampede2/bcast/kt1_st1.csv' --test_file '~/app_ed/datasets/stampede2/bcast/kt1_st1_test.csv' --output_file 'figure3_bcast_cpr.csv' --input_columns 0,1,2 --data_columns 3 --cell_spacing 1,1,1 --ngrid_pts 256,7,8 --cp_rank 12 --reg 1e-5 --build_extrapolation_model 0 --training_set_size 32768
